const { Router } = require('express')

const patientRoutes = require('./patient.routes')
const appointmentRoutes = require('./appointment.routes')
const paymentRoutes = require('./payment.routes')
const billingRoutes = require('./billing.routes')
const receiptRoutes = require('./receipt.routes')
const reportRoutes = require('./report.routes')
const managerReportRoutes = require('./manager-reports.routes')
const userRoutes = require('./user.routes')
const notificationRoutes = require('./notification.routes')
const correctionRoutes = require('./correction.routes')
const waitlistRoutes = require('./waitlist.routes')
const authRoutes = require('./auth.routes')
const consultationRoutes = require('./consultation.routes')
const prescriptionRoutes = require('./prescription.routes')
const imageRoutes = require('./image.routes')
const auditRoutes = require('./audit.routes')

const router = Router()

router.use('/patients', patientRoutes)
router.use('/appointments', appointmentRoutes)
router.use('/payments', paymentRoutes)
router.use('/billing', billingRoutes)
router.use('/receipts', receiptRoutes)
router.use('/reports', reportRoutes)
router.use('/reports', managerReportRoutes)
router.use('/users', userRoutes)
router.use('/notifications', notificationRoutes)
router.use('/', correctionRoutes)
router.use('/waitlist', waitlistRoutes)
router.use('/auth', authRoutes)
router.use('/consultations', consultationRoutes)
router.use('/prescriptions', prescriptionRoutes)
router.use('/images', imageRoutes)
router.use('/audit', auditRoutes)

module.exports = router
